import { NextPage, NextPageContext } from "next";
import Head from "next/head";
import React, { ReactNode } from "react";
import styles from "../styles/MainLayout.module.scss";
import Navbar from "./Navbar";
import Footer from "./Footer";
import { useRouter } from "next/router";
import { useCallback, useEffect, useState } from "react";
interface IProps {
  children: React.ReactNode;
}
const MobileLayout: React.FC<IProps> = ({ children }) => {
  const [title, setTitle] = useState("");
  const router = useRouter();
  const changeTitie = useCallback(() => {
    if (router.asPath === "/") {
      setTitle("关于我们");
    } else if (router.asPath === "/course") {
      setTitle("教学课程");
    } else if (router.asPath === "/news") {
      setTitle("新闻中心");
    } else if (router.asPath === "/studio") {
      setTitle("团队建设");
    } else if (router.asPath === "/graduaexhibition") {
      setTitle("毕业展");
    } else {
      setTitle("");
    }
  }, [router]);
  useEffect(() => {
    changeTitie();
  }, [changeTitie]);
  return (
    <>
      <Head>
        <title>{title}｜浙江理工大学工业设计系</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <div className={styles.mobileContainer}>{children}</div>
      </main>
      <Footer></Footer>
    </>
  );
};

export default MobileLayout;
