import type {NextPage} from "next";
import Head from "next/head";
import styles from "../../styles/graduaexhibition.module.scss";
import MainLayout from "../../components/MainLayout";
import Image from "next/image";
import MobileLayout from "../../components/MobileLayout";
import {LOCAL_URL, MainText, PageNav, Titleswe, TitlesweW, MainTextW} from "../../components/utils";
import {GetServerSideProps, InferGetServerSidePropsType} from "next";
import React, {useEffect, useRef, useState} from "react";
import MobileCards from "../../components/MobileCards";
import GraduationP52022 from "../../components/2022graduationP5";
import GraduationP52022W from "../../components/2022graduationP5W";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import Cards from "../../components/Cards";

const Index: NextPage = ({
                             works,
                         }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const ItemPerPageW = 28;
    const totalPagesCountW = Math.ceil(works.length / ItemPerPageW);
    const totalPagesCount = Math.ceil(works.length / ItemPerPage);
    const preambleRef = useRef<HTMLDivElement>(null)
    const preambleWRef = useRef<HTMLDivElement>(null)
    const [pw, setPw] = useState<number>(0)
    const [pwW, setPwW] = useState<number>(0)
    useEffect(() => {
        setPw(preambleRef.current?.clientWidth as number)
        setPwW(preambleWRef.current?.clientWidth as number)
    }, [pw, pwW])
    return (
        <div>
            <Head>
                <title>交织视界｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <MobileLayout>
                <div className={styles.imageTitle}>
                    <Image
                        src={require("/public/img/graduaexhibition/imageTitle.svg")}
                        alt="imageTitle"
                        height={100}
                        width={386}
                    />
                </div>
                <div className={styles.preamble} ref={preambleRef}>
                    <GraduationP52022 fatherWidth={pw}/>
                </div>
                <div className={styles.preambleTitle}>
                    <Titleswe zh="序言" en="Preamble"/>
                </div>
                <div className={styles.graWorksTitle}>
                    <MainText>
                        全球疫情影响全球各项展览活动基本停摆，人群密集的展会、博物馆、美术馆等受到不同程度的冲击。基于网络
                        空间增设或者重构展品数据信息，抑或强化互联渠道，透过丰富的交互媒介形态，为展品资源拓宽层次丰富、不
                        受时空限制的虚拟线上观看体验。
                        随着云计算技术高度发展，云平台作为一种新型信息技术环境，其具备了多元化的展现形式、即时的互动沟通性
                        能、开放的信息资源共享等特点，成为用户获取信息资源、建立人际关系、获得情感归属、体现自我价值的重要
                        平台。虚拟展馆就是利用计算机图形学的技术构建的数字化展览馆，是一种三维互动体验方式，以传统展馆为基
                        础，利用虚拟技术将展馆及其陈列品移植到互联网上进行展示、宣传与教育活动，突破了传统意义上的时间与空
                        间的局限。
                    </MainText>
                </div>
                <div className={styles.graWorkTitle}>
                    <Titleswe zh="毕业作品" en="Graduation Works"/>
                </div>
                <div className={styles.graWork}>
                    <MobileCards
                        works={works.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    />
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/graduaexhibition`}
                    />
                </div>
            </MobileLayout>
            <MainLayout>
                <div className={styles.imageTitleW}>
                    <Image
                        src={require("/public/img/graduaexhibition/imageTitle.svg")}
                        alt="imageTitle"
                        layout={"fill"}
                        objectFit={"inherit"}
                    />
                </div>
                <div className={styles.preambleW} ref={preambleWRef} style={{height: pwW - 150 - pwW / 4}}>
                    <div className={styles.P5container}>
                        <GraduationP52022W fatherWidth={pwW}/>
                    </div>
                </div>
                <div className={styles.preambleTitleW}>
                    <TitlesweW zh="序言" en="Preamble"/>
                </div>
                <div className={styles.graWorksTitleW}>
                    <MainTextW>
                        全球疫情影响全球各项展览活动基本停摆，人群密集的展会、博物馆、美术馆等受到不同程度的冲击。基于网络
                        空间增设或者重构展品数据信息，抑或强化互联渠道，透过丰富的交互媒介形态，为展品资源拓宽层次丰富、不
                        受时空限制的虚拟线上观看体验。
                        随着云计算技术高度发展，云平台作为一种新型信息技术环境，其具备了多元化的展现形式、即时的互动沟通性
                        能、开放的信息资源共享等特点，成为用户获取信息资源、建立人际关系、获得情感归属、体现自我价值的重要
                        平台。虚拟展馆就是利用计算机图形学的技术构建的数字化展览馆，是一种三维互动体验方式，以传统展馆为基
                        础，利用虚拟技术将展馆及其陈列品移植到互联网上进行展示、宣传与教育活动，突破了传统意义上的时间与空
                        间的局限。
                    </MainTextW>
                </div>
                <div className={styles.graWorkTitleW}>
                    <TitlesweW zh="毕业作品" en="Graduation Works"/>
                </div>
                <div className={styles.graWorkW}>
                    <Cards
                        works={works.slice(
                            (currentPage - 1) * ItemPerPageW,
                            currentPage * ItemPerPageW
                        )}
                    />
                    <div className={styles.pageNav}>
                        <PageNav
                            totalPages={totalPagesCountW}
                            currentPage={currentPage}
                            setPage={SetCurrentPage}
                            pathName={`/graduaexhibition`}
                        />
                    </div>
                </div>
            </MainLayout>
            <Footer/>

        </div>
    );
};
export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://${LOCAL_URL}:1337/graduation-works?_sort=published_at:DESC`);
    const data = await res.json();
    // console.log(data);
    const works = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/graduaexhibition/${a.id}`,
    }));
    // console.log(works)
    return {
        props: {
            works: works,
        },
    };
};
export default Index;
