import type {
    GetServerSideProps,
    InferGetServerSidePropsType,
    NextPage,
} from "next";
import Image from "next/image";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../../styles/news.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import Link from "next/link";
import MobileCards from "../../components/MobileCards";
import React, {useEffect, useRef, useState} from "react";
import {BannerM, LOCAL_URL, MainTextW, PageNav, Title1W, Titleswe, TitlesweW} from "../../components/utils";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import gsap from "gsap";
import Cards from "../../components/Cards";

const News: NextPage = ({
                            news,
                            banner
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const totalPagesCount = Math.ceil(news.length / ItemPerPage);
    const titleSquare = useRef<HTMLDivElement>(null);
    const [linkHover, setLinkHover] = useState(0)
    const ItemPerPageW = 28;
    const totalPagesCountW = Math.ceil(news.length / ItemPerPageW);

    const handleMouseOver = (i: number) => {
        setLinkHover(i)
    }
    const handleMouseLeave = () => {
        setLinkHover(0)
    }
    useEffect(() => {
        gsap.to(titleSquare.current, {
            width: "95%",
            duration: 3
        })
    }, [])
    return (
        <div>
            <Head>
                <title>新闻中心｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/news/imageTitle.png")}
                        alt="imageTitle"
                        height={95}
                        width={391}
                    />
                </div>
                <div className={styles.category}>
                    <div className={styles.tongzhi}>
                        <Link href="/news/tongzhi">
                            <a>
                                <Image
                                    src={require("/public/img/news/tongzhi.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.jiangzuo}>
                        <Link href="/news/jiangzuo">
                            <a>
                                <Image
                                    src={require("/public/img/news/jiantgzuo.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>

                    <div className={styles.zhanxun}>
                        <Link href="/news/zhanxun">
                            <a>
                                <Image
                                    src={require("/public/img/news/zhanxun.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                </div>
                <div className={styles.swipper}>
                    <BannerM bannerData={banner}/>
                </div>
                <div className={styles.contentTitle}>
                    <Titleswe zh="全部新闻" en="All News"/>
                </div>
                <div className={styles.contents}>
                    <MobileCards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    />
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/news`}
                    />
                </div>
            </MobileLayout>
            <MainLayout>
                <div className={styles.navW}>
                    <div className={styles.title}>
                        <div className={styles.left}>
                            <Image src={require("/public/img/news/NE.png")} alt={"titleL"}/>
                        </div>
                        <div className={styles.mid}>
                            <div className={styles.square} ref={titleSquare}/>
                        </div>
                        <div className={styles.right}>
                            <Image src={require("/public/img/news/WS.png")} alt={"titleR"}/>
                        </div>
                    </div>
                    <div className={styles.select}>
                        <Link href={"/news/tongzhi"}>
                            <a className={`${styles.choice} ${styles.tongzhi}`}
                               onMouseOver={() => {
                                   handleMouseOver(1)
                               }}
                               onMouseLeave={() => {
                                   handleMouseLeave()
                               }}>
                                <Image
                                    src={require("../../public/img/news/select/tongzhi.svg")}
                                    alt="工业设计手绘"
                                    layout={"fill"}
                                    objectFit={"contain"}
                                />
                                <Image
                                    src={require("../../public/img/news/select/tongzhiH.svg")}
                                    alt="工业设计手绘"
                                    layout={"fill"}
                                    objectFit={"contain"}
                                    style={{visibility: linkHover === 1 ? "visible" : "hidden"}}
                                />
                            </a>
                        </Link>
                        <Link href={"/news/zhanxun"}>
                            <a className={`${styles.choice} ${styles.zhanxun}`}
                               onMouseOver={() => {
                                   handleMouseOver(2)
                               }}
                               onMouseLeave={() => {
                                   handleMouseLeave()
                               }}>
                                <Image
                                    src={require("../../public/img/news/select/zhanxun.svg")}
                                    alt="基础设计"
                                    layout={"fill"}
                                    objectFit={"contain"}

                                />
                                <Image
                                    src={require("../../public/img/news/select/zhanxunH.svg")}
                                    alt="基础设计"
                                    layout={"fill"}
                                    objectFit={"contain"}
                                    style={{visibility: linkHover === 2 ? "visible" : "hidden"}}
                                />
                            </a>
                        </Link>
                        <Link href={"/news/jiangzuo"}>
                            <a className={`${styles.choice} ${styles.jiangzuo}`}
                               onMouseOver={() => {
                                   handleMouseOver(3)
                               }}
                               onMouseLeave={() => {
                                   handleMouseLeave()
                               }}>
                                <Image
                                    src={require("../../public/img/news/select/jiangzuo.svg")}
                                    alt="基础设计"
                                    layout={"fill"}
                                    objectFit={"contain"}

                                />
                                <Image
                                    src={require("../../public/img/news/select/jiangzuoH.svg")}
                                    alt="基础设计"
                                    layout={"fill"}
                                    objectFit={"contain"}
                                    style={{visibility: linkHover === 3 ? "visible" : "hidden"}}
                                />
                            </a>
                        </Link>
                    </div>

                    <div className={styles.swipperW}>
                        <BannerM bannerData={banner}/>
                    </div>
                </div>
                <div className={styles.newsTitleW}>
                    <TitlesweW zh="全部新闻" en="All News"/>
                </div>
                <div className={styles.newsW}>
                    <Cards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPageW,
                            currentPage * ItemPerPageW
                        )}
                    />
                    <div className={styles.pageNav}>
                        <PageNav
                            totalPages={totalPagesCountW}
                            currentPage={currentPage}
                            setPage={SetCurrentPage}
                            pathName={`/graduaexhibition`}
                        />
                    </div>
                </div>
            </MainLayout>
            <Footer/>

        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://${LOCAL_URL}:1337/news-centers`);
    const data = await res.json();
    const bannerRes = await fetch(`http://${LOCAL_URL}:1337/news-banner`);
    const bannerData = await bannerRes.json()
    const banner = {
        bannerItem1: {
            url: bannerData["news"]["bannerItems1"].url,
            coverUrl: bannerData["news"]["bannerItems1"].cover.url
        },
        bannerItem2: {
            url: bannerData["news"]["bannerItmes2"].url,
            coverUrl: bannerData["news"]["bannerItmes2"].cover.url
        },
        bannerItem3: {
            url: bannerData["news"]["bannerItem3"].url,
            coverUrl: bannerData["news"]["bannerItem3"].cover.url
        },
    }
    // console.log(data);
    const news = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/news/${a.id}`,
    }));


    return {
        props: {
            news: news,
            banner: banner
        },
    };
};
export default News;
