import type {
    GetServerSideProps,
    InferGetServerSidePropsType,
    NextPage,
} from "next";
import Image from "next/image";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../../styles/news.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import Link from "next/link";
import MobileCards from "../../components/MobileCards";
import React, {useState} from "react";
import {BannerM, PageNav, Titleswe} from "../../components/utils";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const News: NextPage = ({
                            news,
                            banner
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const totalPagesCount = Math.ceil(news.length / ItemPerPage);

    return (
        <div>
            <Head>
                <title>新闻中心｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/news/imageTitle.png")}
                        alt="imageTitle"
                        height={95}
                        width={391}
                    />
                </div>
                <div className={styles.category}>
                    <div className={styles.tongzhi}>
                        <Link href="/news/tongzhi">
                            <a>
                                <Image
                                    src={require("/public/img/news/tongzhi.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.jiangzuo}>
                        <Link href="/news/jiangzuo">
                            <a>
                                <Image
                                    src={require("/public/img/news/jiantgzuo.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>

                    <div className={styles.zhanxun}>
                        <Link href="/news/zhanxun">
                            <a>
                                <Image
                                    src={require("/public/img/news/zhanxun.png")}
                                    alt="imageTitle"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                </div>
                <div className={styles.swipper}>
                    <BannerM bannerData={banner}/>
                </div>
                <div className={styles.contentTitle}>
                    <Titleswe zh="全部新闻" en="All News"/>
                </div>
                <div className={styles.contents}>
                    <MobileCards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    />
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/news`}
                    />
                </div>
            </MobileLayout>
            <Footer/>

        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://127.0.0.1:1337/news-centers`);
    const data = await res.json();
    const bannerRes = await fetch(`http://127.0.0.1:1337/news-banner`);
    const bannerData = await bannerRes.json()
    const banner = {
        bannerItem1: {
            url: bannerData["news"]["bannerItems1"].url,
            coverUrl: bannerData["news"]["bannerItems1"].cover.url
        },
        bannerItem2: {
            url: bannerData["news"]["bannerItmes2"].url,
            coverUrl: bannerData["news"]["bannerItmes2"].cover.url
        },
        bannerItem3: {
            url: bannerData["news"]["bannerItem3"].url,
            coverUrl: bannerData["news"]["bannerItem3"].cover.url
        },
    }
    // console.log(data);
    const news = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/news/${a.id}`,
    }));


    return {
        props: {
            news: news,
            banner: banner
        },
    };
};
export default News;
