import type {
    GetServerSideProps,
    InferGetServerSidePropsType,
    NextPage,
} from "next";
import Image from "next/image";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../../styles/news.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import Link from "next/link";
import {BannerM, PageNav, Titleswe} from "../../components/utils";
import {useState} from "react";
import MobileCards from "../../components/MobileCards";

const News: NextPage = ({
                            news,
                            banner
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const totalPagesCount = Math.ceil(news.length / ItemPerPage);
    return (
        <div>
            <Head>
                <title>讲座｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/news/jiangzuoTitle.png")}
                        alt="imageTitle"
                        height={95}
                        width={390}
                    ></Image>
                </div>
                <div className={styles.swipper}>
                    <BannerM bannerData={banner}/>

                </div>
                <div className={styles.contentTitle}>
                    <Titleswe zh="讲座" en="Lecture"></Titleswe>
                </div>
                <div className={styles.contents}>
                    <MobileCards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    ></MobileCards>
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/news/jiangzuo`}
                    ></PageNav>
                </div>
            </MobileLayout>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://127.0.0.1:1337/news-centers?news_category=1`);
    const data = await res.json();
    const bannerRes = await fetch(`http://127.0.0.1:1337/news-banner`);
    const bannerData = await bannerRes.json()
    const banner = {
        bannerItem1: {
            url: bannerData["jiangzuo"]["bannerItems1"].url,
            coverUrl: bannerData["jiangzuo"]["bannerItems1"].cover.url
        },
        bannerItem2: {
            url: bannerData["jiangzuo"]["bannerItmes2"].url,
            coverUrl: bannerData["jiangzuo"]["bannerItmes2"].cover.url
        },
        bannerItem3: {
            url: bannerData["jiangzuo"]["bannerItem3"].url,
            coverUrl: bannerData["jiangzuo"]["bannerItem3"].cover.url
        },
    }
    // console.log(data);
    const news = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/news/${a.id}`,
    }));
    // console.log(news)
    return {
        props: {
            news: news,
            banner: banner
        },
    };
};
export default News;
