import type {
    GetServerSideProps,
    InferGetServerSidePropsType,
    NextPage,
} from "next";
import Image from "next/image";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../../styles/news.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import Link from "next/link";
import {BannerM, LOCAL_URL, PageNav, Titleswe} from "../../components/utils";
import React, {useState} from "react";
import MobileCards from "../../components/MobileCards";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const News: NextPage = ({
                            news,
    banner
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const totalPagesCount = Math.ceil(news.length / ItemPerPage);
    return (
        <div>
            <Head>
                <title>通知｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>

            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/news/jiangzuoTitle.png")}
                        alt="imageTitle"
                        height={95}
                        width={390}
                    />
                </div>
                <div className={styles.swipper}>
                    <BannerM bannerData={banner}/>
                </div>
                <div className={styles.contentTitle}>
                    <Titleswe zh="通知" en="Notice"/>
                </div>
                <div className={styles.contents}>
                    <MobileCards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    />
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/news/tongzhi`}
                    />
                </div>
            </MobileLayout>
            <Footer/>

        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://${LOCAL_URL}/news-centers?news_category=2`);
    const data = await res.json();
    const bannerRes = await fetch(`http://${LOCAL_URL}/news-banner`);
    const bannerData = await bannerRes.json()
    const banner = {
        bannerItem1: {
            url: bannerData["tongzhi"]["bannerItems1"].url,
            coverUrl: bannerData["tongzhi"]["bannerItems1"].cover.url
        },
        bannerItem2: {
            url: bannerData["tongzhi"]["bannerItmes2"].url,
            coverUrl: bannerData["tongzhi"]["bannerItmes2"].cover.url
        },
        bannerItem3: {
            url: bannerData["tongzhi"]["bannerItem3"].url,
            coverUrl: bannerData["tongzhi"]["bannerItem3"].cover.url
        },
    }
    // console.log(data);
    const news = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/news/${a.id}`,
    }));
    // console.log(news)
    return {
        props: {
            news: news,
            banner:banner
        },
    };
};
export default News;
