import type {
    GetServerSideProps,
    InferGetServerSidePropsType,
    NextPage,
} from "next";
import Image from "next/image";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../../styles/news.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import Link from "next/link";
import {PageNav, Titleswe} from "../../components/utils";
import {useState} from "react";
import MobileCards from "../../components/MobileCards";

const News: NextPage = ({
                            news,
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const [currentPage, SetCurrentPage] = useState(1);
    const ItemPerPage = 12;
    const totalPagesCount = Math.ceil(news.length / ItemPerPage);
    return (
        <div>
            <Head>
                <title>展讯｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/news/jiangzuoTitle.png")}
                        alt="imageTitle"
                        height={95}
                        width={390}
                    />
                </div>
                <div className={styles.swipper}/>
                <div className={styles.contentTitle}>
                    <Titleswe zh="展讯" en="Spreadtrum"/>
                </div>
                <div className={styles.contents}>
                    <MobileCards
                        works={news.slice(
                            (currentPage - 1) * ItemPerPage,
                            currentPage * ItemPerPage
                        )}
                    />
                    <PageNav
                        totalPages={totalPagesCount}
                        currentPage={currentPage}
                        setPage={SetCurrentPage}
                        pathName={`/news/zhanxun`}
                    />
                </div>
            </MobileLayout>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async context => {
    const res = await fetch(`http://127.0.0.1:1337/news-centers?news_category=3`);
    const data = await res.json();
    // .log(data);
    const news = data.map((a: any) => ({
        title: a.title,
        published_at: a.published_at,
        author: a.author,
        cover: a.cover,
        url: `/news/${a.id}`,
    }));
    // .log(news);
    return {
        props: {
            news: news,
        },
    };
};
export default News;
