import type {NextPage} from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/studios.module.scss";
import MainLayout from "../../components/MainLayout";
import MobileLayout from "../../components/MobileLayout";
import {MainText, Titleswe} from "../../components/utils";
import Link from "next/link";
import Navbar from "../../components/Navbar";
import React from "react";
import Footer from "../../components/Footer";

interface categray {
    fwsjyshcx: string;
    kcxsj: string;
    qdyjs: string;
    szwc: string;
    jjsj: string;
}

const courses: categray = {
    fwsjyshcx: "工业设计手绘",
    kcxsj: "基础设计",
    qdyjs: "人机工程学",
    szwc: "原型控制与交互",
    jjsj: "设计图学",
};
const Studio: NextPage = () => {
    return (
        <div>
            <Head>
                <title>团队建设｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>

            <MobileLayout>
                <div className={styles.titleImage}>
                    <Image
                        src={require("/public/img/studio/titleImage.png")}
                        alt="imageTitle"
                        height={95}
                        width={391}
                    />
                </div>
                <div className={styles.categories}>
                    <div className={styles.fwsjyshcx}>
                        <Link href="/studio/fwsjyshcx">
                            <a>
                                <Image
                                    src={require("/public/img/studio/category/fwsjyshcx.png")}
                                    alt="fwsjyshcx"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.szwc}>
                        <Link href="/studio/szwc">
                            <a>
                                <Image
                                    src={require("/public/img/studio/category/szwc.png")}
                                    alt="szwc"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.kcxsj}>
                        <Link href="/studio/kcxsj">
                            <a>
                                <Image
                                    src={require("/public/img/studio/category/kcxsj.png")}
                                    alt="kcxsj"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.jjsj}>
                        <Link href="/studio/jjsj">
                            <a>
                                <Image
                                    src={require("/public/img/studio/category/jjsj.png")}
                                    alt="jjsj"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                    <div className={styles.qdyjs}>
                        <Link href="/studio/qdyjs">
                            <a>
                                <Image
                                    src={require("/public/img/studio/category/qdyjs.png")}
                                    alt="qdyjs"
                                    height={120}
                                    width={120}
                                />
                            </a>
                        </Link>
                    </div>
                </div>
                <div className={styles.overviewTitles}>
                    <Titleswe zh="工作室概览" en="Studio Overview"/>
                </div>
                <div className={styles.overview}>
                    <MainText>
                        团队目前有专职教师29名，其中教授4名、副教授9名，博士18名（含在读），有海外留学访学经历的11人。享受国务院特殊津贴专家1名，浙江省151人才1名，浙江省学科带头人1名，浙江省优秀教师1名，浙江省教坛新秀1名，校教坛新秀5名，校三育人先进个人6名，校“521计划”拔尖人才1名、骨干人才4名，金富春教学奖2名，五四青年奖章2名，华鼎奖教金3名，双高双强教师3名，由家具行业协会认定的首批全国家具十佳设计师1名，以及浙江省十佳工业设计推进者2名。
                    </MainText>
                </div>
                <div className={styles.resultsTitle}>
                    <Titleswe zh="现有成果" en="On-going results"/>
                </div>
                <div className={styles.results}/>
            </MobileLayout>
            <Footer/>

        </div>
    );
};

export default Studio;

