import type { NextPage } from "next";
import styles from "../styles/course.module.scss";
import MainLayout from "../components/MainLayout";
import Image from "next/image";
import { MainText, Title1 } from "../components/utils";
import MobileLayout from "../components/MobileLayout";
import Link from "next/link";
import Head from "next/head";

const Course: NextPage = () => {
  return (
    <div>
      <Head>
        <title>教学课程｜浙江理工大学工业设计系</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileLayout>
        <div className={styles.nav}>
          <div className={styles.title}>
            <Image
              src={require("../public/img/course/title.svg")}
              alt="title"
            ></Image>
          </div>
          <div className={styles.select}>
            <Link href={"/courseDetail/gysjsh"}>
              <a className={`${styles.choice} ${styles.gongyesheji}`}>
                <Image
                  src={require("../public/img/course/select/gongyesheji.svg")}
                  alt="工业设计手绘"
                ></Image>
              </a>
            </Link>
            <Link href={"/courseDetail/jcsj"}>
              <a className={`${styles.choice} ${styles.jichusheji}`}>
                <Image
                  src={require("../public/img/course/select/jichusheji.svg")}
                  alt="基础设计"
                ></Image>
              </a>
            </Link>
            <Link href={"/courseDetail/sjtx"}>
              <a className={`${styles.choice} ${styles.shejituxue}`}>
                <Image
                  src={require("../public/img/course/select/shejituxue.svg")}
                  alt="设计图学"
                ></Image>
              </a>
            </Link>
            <Link href={"/courseDetail/yxkzyjh"}>
              <a className={`${styles.choice} ${styles.yuanxinkongzhi}`}>
                <Image
                  src={require("../public/img/course/select/yuanxingkongzhi.svg")}
                  alt="原型控制与交互"
                ></Image>
              </a>
            </Link>
            <Link href={"/courseDetail/rjgcx"}>
              <a className={`${styles.choice} ${styles.renjigongcheng}`}>
                <Image
                  src={require("../public/img/course/select/renji.svg")}
                  alt="人机工程学"
                ></Image>
              </a>
            </Link>
          </div>
        </div>
        <div className={styles.content}>
          <div className={styles.titles}>
            <Title1>课程总述</Title1>
            <Title1>Course Introduction</Title1>
          </div>
          <MainText>
            专业目前有国家精品资源共享课、国家视频公开课各1门，国家级工程实践教育中心1个，浙江省精品在线开放课程2门，19门数字教学课件获全国、省级奖项，教材10余本，以及《设计图学》、《工业设计手绘》等另10门在线开放课程在建培育。近几年教学成果“艺术设计类课程E-CO数字化生态环境构建及其学习模式改革”、“行业特色地方高校本科拔尖人才培养的探索与实践”均获国家教学成果奖二等奖，另有浙江省教学成果奖4项，中国纺织工业联合会教学成果奖6项，浙江省高校“互联网+教学”优秀案例一等奖1项。
          </MainText>
        </div>
      </MobileLayout>
    </div>
  );
};

export default Course;
