import type {NextPage} from "next";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.scss";
import MainLayout from "../components/MainLayout";
import React, {useRef} from "react";
import {useEffect} from "react";
import Image from 'next/image'
import MobileLayout from "../components/MobileLayout";
import {
    BannerM,
    Features,
    History,
    HistoryW,
    historyProps,
    HomeContent,
    HomeContentW,
    LOCAL_URL,
    Talent,
    FeaturesW,
    tidyUrl,
    Titleswe, MainTextW, TalentW,TitlesweW
} from "../components/utils";
import {GetServerSideProps, InferGetServerSidePropsType} from "next";
import Box from "../components/BoxM";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";


const Home: NextPage = ({
                            talents,
                            featuresM,
                            honor,
                            banner,
                            histories,
                            features
                        }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

    return (
        <div>
            <Head>
                <title>关于我们｜浙江理工大学工业设计系</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>

            <MobileLayout>
                <div className={styles.mainGraph}>
                    <div className={styles.texts}>
                        <HomeContent/>
                    </div>
                    <div className={styles.circle}/>
                    <Box left={0}/>
                </div>
                <div className={styles.swipper}>
                    <BannerM bannerData={banner}/>
                </div>
                <div className={styles.history}>
                    <div className={styles.title}>
                        <Titleswe zh="历史沿革" en="Development History"/>
                    </div>
                    <History historyData={histories}/>
                </div>
                <div className={styles.feature}>
                    <div className={styles.title}>
                        <Titleswe zh="特色优势" en="Features and advantages"/>
                    </div>
                    <Features content={featuresM}/>
                </div>
                <div className={styles.honor}>
                    <div className={styles.title}>
                        <Titleswe zh="荣誉与成果" en="Honor and Achievement"/>
                    </div>
                    <div className={styles.honorImg}>
                        <Image src={tidyUrl(honor)} alt={"honor"} layout={"fill"} objectFit={"contain"}/>
                    </div>
                </div>
                <div className={styles.talent}>
                    <div className={styles.title}>
                        <Titleswe zh="人才培养" en="Cultivation of talents"/>
                    </div>
                    <Talent talents={talents}/>
                </div>
            </MobileLayout>
            <MainLayout>
                <div className={styles.mainGraphW}>
                    <div className={styles.texts}>
                        <HomeContentW/>
                    </div>
                    <Box left={5}/>
                </div>
                <div className={styles.swipperW}>
                    <BannerM bannerData={banner}/>
                </div>
                <div className={styles.featureW}>
                    <div className={styles.title}>
                        <TitlesweW zh="特色优势" en="Features and advantages"/>
                    </div>
                    <FeaturesW content={features}/>
                </div>
                <div className={styles.historyW}>
                    <div className={styles.title}>
                        <TitlesweW zh="历史沿革" en="Development History"/>
                    </div>
                    <HistoryW historyData={histories}/>
                    <div className={styles.content}>
                        <MainTextW>
                            专业于1996年开始本科招生，2000年获硕士点，现为国家一流本科专业建设点、省“十三五”、“十二五”特色专业、教育部卓越工程师计划试点专业、省大学生工业设计竞赛秘书处单位，所在学科入选浙江省一流学科（A类）。2018专业排名全国25名/245（武书连2018大学本科专业排行榜），2019专业排名全国10名/223（2019中国大学本科教育分专业竞争力排行榜），专业评估为五星专业。
                        </MainTextW>
                    </div>
                </div>

                <div className={styles.honorW}>
                    <div className={styles.title}>
                        <TitlesweW zh="荣誉与成果" en="Honor and Achievement"/>
                    </div>
                    <div className={styles.honorImg}>
                        <Image src={tidyUrl(honor)} alt={"honor"} width={1200} height={714.42}/>
                    </div>
                </div>
                <div className={styles.talentW}>
                    <div className={styles.title}>
                        <TitlesweW zh="人才培养" en="Cultivation of Talents"/>
                    </div>
                    <TalentW talents={talents}/>
                </div>
            </MainLayout>
            <Footer/>
        </div>
    );
};


export const getServerSideProps: GetServerSideProps = async context => {
        const res = await fetch(`http://${LOCAL_URL}:1337/about-us`);
        const data = await res.json() as any;
        const talents = data["talents"].map((e: any) => ({
            title: e.title,
            content: e.describe
        }))
        const featuresM: string[] = []
        data["features"].map((e: any) => {
            featuresM.push(e.title)
        })

        const features = data["features"].map((e: any) => (
            {
                title: e.title,
                imgUrl: e.cover.url
            }
        ))

        const honor = data["honor"].url
        const banner = {
            bannerItem1: {
                url: data["banner"]["bannerItems1"].url,
                coverUrl: data["banner"]["bannerItems1"].cover.url
            },
            bannerItem2: {
                url: data["banner"]["bannerItmes2"].url,
                coverUrl: data["banner"]["bannerItmes2"].cover.url
            },
            bannerItem3: {
                url: data["banner"]["bannerItem3"].url,
                coverUrl: data["banner"]["bannerItem3"].cover.url
            },
        }

        const histories: historyProps = data["history"].map((e: { year: any; content: any; }) => (
            {
                year: e.year,
                event_: e.content
            }
        ))
        // console.log(featuresM)
        return {
            props: {
                talents: talents,
                featuresM: featuresM,
                honor: honor,
                banner: banner,
                histories: histories,
                features: features
            },
        };
    }
;


export default Home;
