import type { NextPage } from "next";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.scss";
import MainLayout from "../components/MainLayout";
import { useRef } from "react";
import { useEffect } from "react";
import MobileLayout from "../components/MobileLayout";
import { Titleswe } from "../components/utils";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>关于我们｜浙江理工大学工业设计系</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileLayout>
        <div className={styles.mainGraph}></div>
        <div className={styles.swipper}></div>
        <div className={styles.history}>
          <div className={styles.title}>
            <Titleswe zh="历史沿革" en="Development History"></Titleswe>
          </div>
        </div>
        <div className={styles.feature}>
          <div className={styles.title}>
            <Titleswe zh="特色优势" en="Features and advantages"></Titleswe>
          </div>
        </div>
        <div className={styles.honor}>
          <div className={styles.title}>
            <Titleswe zh="荣誉与成果" en="Honor and Aachievement"></Titleswe>
          </div>
        </div>
        <div className={styles.talent}>
          <div className={styles.title}>
            <Titleswe zh="人才培养" en="Cultivation of talents"></Titleswe>
          </div>
        </div>
      </MobileLayout>
    </div>
  );
};

export default Home;
