import type { NextPage } from "next";
import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.scss";
import MainLayout from "../components/MainLayout";
const News: NextPage = () => {
  return (
    <div>
    <Head>
      <title>毕业展｜浙江理工大学工业设计系</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <MainLayout>
      <div className={styles.test}></div>
    </MainLayout>
  </div>
  );
};

export default News;
