// Copyright (c) 2022 drafff
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

import styles from "../../../styles/studios.module.scss";
import MainLayout from "../../../../components/MainLayout";
import MobileLayout from "../../../../components/MobileLayout";
import Image from "next/image";
import { NextPage } from "next";
import Head from "next/head";
import { MainText, Titleswe } from "../../../../components/utils";
interface categray {
  fwsjyshcx: string;
  kcxsj: string;
  qdyjs: string;
  szwc: string;
  jjsj: string;
}
const courses: categray = {
  fwsjyshcx: "工业设计手绘",
  kcxsj: "基础设计",
  qdyjs: "人机工程学",
  szwc: "原型控制与交互",
  jjsj: "设计图学",
};
const Pages: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>团队建设｜浙江理工大学工业设计系</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileLayout>
        <div className={styles.titleImage}>
          <Image
            src={require("/public/img/studio/titleImage.png")}
            alt="imageTitle"
            height={95}
            width={391}
          ></Image>
        </div>

        <div className={styles.introTitle}>
          <Titleswe zh="工作室介绍" en="Studio Introduction"></Titleswe>
        </div>
        <div className={styles.intro}>
          <MainText>
          团队目前有专职教师29名，其中教授4名、副教授9名，博士18名（含在读），有海外留学访学经历的11人。享受国务院特殊津贴专家1名，浙江省151人才1名，浙江省学科带头人1名，浙江省优秀教师1名，浙江省教坛新秀1名，校教坛新秀5名，校三育人先进个人6名，校“521计划”拔尖人才1名、骨干人才4名，金富春教学奖2名，五四青年奖章2名，华鼎奖教金3名，双高双强教师3名，由家具行业协会认定的首批全国家具十佳设计师1名，以及浙江省十佳工业设计推进者2名。
          </MainText>
        </div>
        <div className={styles.directionTitle}>
          <Titleswe zh="研究方向" en="Research direction"></Titleswe>
        </div>
        <div className={styles.direction}></div>
        <div className={styles.personnelTitle}>
          <Titleswe zh="人员架构" en="Personnel"></Titleswe>
        </div>
        <div className={styles.personnel}></div>
        <div className={styles.resultTitle}>
          <Titleswe zh="具体成果" en="Concrete results"></Titleswe>
        </div>
        <div className={styles.result}></div>
      </MobileLayout>
    </div>
  );
};

export default Pages;
